### ISSUE TITLE
NPE in CDIUtil when firing CDI event from background thread

### ISSUE THREAD

**Issue by antonsimola** [vaadin/cdi#226]
I'm trying to fire event from background thread. I'm trying to notify Vaadin Views as well as one basic Singleton bean with the same event. in case of background task, I don't have any views when the event is fired (background task might be running without UI), so I'm expecting that the Singleton only receives the event.  The event firing works when I have UI running at the time of the background task. But if I don't have Vaadin Session running, I get NPE. Possibly some beans are still available in the container and are trying to get notified of the event, but NPE happens in CDIUtil:64 (cdi plugin 1.0.2, also same NPE possibility in 2.0)         Long id = (Long) session.getAttribute("cdi-session-id");

**Comment by TatuLund** [comment]
I think this is not actually a bug.
If you use CDIEvent from background threads, you need to set 

```
private void backgroundProcess(final UI ui) {
    VaadinSession.setCurrent(ui.getSession());
    UI.setCurrent(ui);	
    ...
}
```

And start  it this way

```
UI ui = UI.getCurrent();
executor.submit(new Runnable() {
    @Override
    public void run() {
          backgroundProcess(ui);
    }
});
```

**Comment by Legioth** [comment]
I'd claim that it's still a bug if an `NPE` is thrown. Instead, the implementation should throw a more helpful exception that explains what is actually wrong.

I would also strongly discourage against arbitrarily calling `setCurrent` for e.g. `UI` or `VaadinSession` since that will most likely mean that those instances are used in situations where the session isn't properly locked. Instead, anything that directly or indirectly relies on a UI or session should be using `UI.access` to ensure proper synchronization.

**Comment by TatuLund** [comment]
Yes. The workaround is a hack, and works only when you can have your background service UIScoped. If you need to fire CDIEvent from ApplicationScope to all UI's this is blocking issue, which you cannot solve by the workaround mentioned above.

**Comment by nuKle0ni** [comment]
Sorry, I'm not working anymore on the project where this issue happened. But basically the situation was that you would have two ways of invoking background task: 

1. Button is pressed in the UI -> run background task -> fire BackgroundTaskFinishedEvent-> refresh views (DTOs changed) and update something in Singleton  -> everything OK
2. Same background task invoked in CRON fashion (no UI, possibly no users logged in) -> fire BackgroundTaskFinishedEvent -> at this point I would assume that only the Singleton (nothing to do with Vaadin) would be notified, but I would still get NPE from Vaadin CDI code (as in previous comment), because it was practically trying to find views for the session to be notified. 

I could not have done the above workaround since there's no UI to bind the background task into.

I believe there may have been other workaround such as checking if there's no session then fire other kind of event meant for just the Singleton.

And yes @TatuLund  I don't think I would have been able to scope the background service UIScoped since it was supposed to run independently of UI.

Maybe I'm understanding it wrong how the events should work. Hope you get my point though.

**Comment by TatuLund** [comment]
See also https://github.com/vaadin/cdi/issues/102
