### ISSUE TITLE
Vaadin CDI Event Observer Chat Demo

### ISSUE THREAD

**Issue by BlumadeDeveloper** [vaadin/cdi#235]
Seems that Vaadin CDI Event with CDIView does't work as expected in versione 3.0, in version 2.0 it works.

The CDI event is fired in UI.access but not received on CDIView(s) that contains the Observers method.

To test this behaviour: https://github.com/vaadin/cdi-tutorial/tree/master/src/main/java/com/vaadin/cdi/tutorial

**Comment by tsuoanttila** [comment]
The tutorial is outdated for 3.0, I will try to push a fix to various issues with it soon. 

The main issue is that the tutorial does not use `CDINavigator` but uses an old workaround on the issue. This leads to scopes not working properly. Changing the navigation so that in `MyVaadinUI` you `@Inject CDINavigator navigator;` and in the `UI::init` you call `navigator.init(this, this)`. Remove the whole NavigationEvent and replace all calls related to it to `getUI().getNavigator().navigateTo(<viewnamehere>)`. The `NavigationLogDecorator` does not work anymore the same way but you can make a much simpler implementation with `observeNavigation(@Observes @AfterViewChange ViewChangeEvent event)`.

**Comment by BlumadeDeveloper** [comment]
Thank you very much for the solution.
I have try it and seems that all work like a charm.
