### ISSUE TITLE
Fails to deploy on WebSphere 8.5.5.14

### ISSUE THREAD

**Issue by anders-special** [vaadin/cdi#277]
We are migrating our application from Vaadin 8 to Vaadin 12. Unfortunately the application refuses to deploy on IBM WebSphere 8.5.5.14. The following error is logged during application deployment.

... Caused by: com.ibm.ws.exception.RuntimeWarning: com.ibm.ws.webcontainer.exception.WebAppNotLoadedException: Failed to load webapp: Failed to load webapp: WebBeans with api type with normal scope must be proxiable to inject. com.vaadin.cdi.context.AbstractContextualStorageManager has no explicit no-arg constructor!A public or protected constructor without args is required! ...

My conclusion is that the problem is with the WebSphere validation of the classes. It requires the class AbstractContextualStorageManager to have an empty constructor. I believe that the only thing necessary to make this addon compatible with WebSphere is to add the following constructor.

protected AbstractContextualStorageManager () {
    this(false);
}

I am aware of that the class is abstract and that it does not really make sense to have an empty constructor. But I have no other suggestion how to solve the problem.

**Comment by kumm** [comment]
WAS 8.5.5.* is jee6 compliant. - according to https://developer.ibm.com/answers/questions/291731/what-version-of-cdi-spec-supported-by-was-8559/ - 
It provides CDI api 1.0, and servlet api 3.0.
This CDI addon depends on CDI api 1.2 from jee7.
Vaadin 12 - and even 10 - depends on sevlet api 3.1 from jee7 too. 

I've tried the constructor as you mentioned. It fails as it should. 
The next problem is: `java.lang.ClassNotFoundException: javax.enterprise.context.spi.AlterableContext`.
Class exists only from CDI 1.2.

The plain vaadin starter project from here https://github.com/vaadin/beverage-starter-flow fails to deploy too.

After downgrading the servlet dependency in vaadin flow to 3.0 it does not compile. Vaadin use some part of the servlet 3.1 api.

Going to check WAS9, and liberty.

**Comment by kumm** [comment]
According to my tests liberty profile almost works (tried version 17, and 18). I've found a weird problem with servlet registration, created https://github.com/OpenLiberty/open-liberty/issues/6094. 
Disabling the CDI servlet, and serving frontend files in developement mode does not work. I've found an easy workaround, await for response.

WAS9 does not work form me even with plain vaadin starter project.
Route discovery on deploy fails, because the annotation classes `Route.class`, and `RouteAlias.class` are provided as route classes by the application server ( it shoud not ) for `RouteRegistryInitializer`.
This is not CDI related, you should contact with vaadin flow project whether WAS9 is supported or not.

**Comment by Legioth** [comment]
As stated in the release notes, Vaadin 12 supports 8.5 Liberty Profile, but not the regular 8.5 series. https://github.com/vaadin/platform/releases/tag/12.0.0. This should maybe be further clarified since Liberty Profile only supports CDI 1.2 as of version 8.5.5.6.

There's already a ticket open for Flow about supporting the non-standard handling of `@HandlesTypes` in https://github.com/vaadin/flow/issues/4901.

**Comment by anders-special** [comment]
I managed to get Vaadin 12 to work on WebSphere 8.5.5.14 by making the following changes.
1. Vaadin CDI - AbstractContextualStorageManager - added empty constructor.
2. Vaadin CDI - VaadinSessionScopedContext - changed the passivationCapable parameter to false.
3. Vaadin Flow - AbstractRouteRegistryInitializer - added null check in the methods validateRouteImplementation and validateRouteAnnotation.
4. Vaadin Flow - ResponseWriter - changed the method call to setContentLengthLong to setContentLength.
