### ISSUE TITLE
External @EJB or @Inject are null with Flow and CDI 10

### ISSUE THREAD

**Issue by madduci** [vaadin/cdi#278]
Hi,

As I've highlighted on a [StackOverflow answer](https://stackoverflow.com/questions/54474621/vaadin-12-pwa-with-cdi-and-existing-jax-rs-service), I'm having problems with Flow/PWA and CDI, because I'm getting always NullpointerException on classes that are defined in other Maven Modules.

With Vaadin 8 and @CDIUI the same injection works. What is wrong?

**Comment by kumm** [comment]
According to the stacktrace the CDI beanmanager can't resolve a bean for the class `thorntail.elytron.wui.MainView`, and the instantiator falls back to the default vaadin instatiation. 
Some guessing:
- is there a class extending this one?
- do you have a beans.xml with bean-discovery-mode annotated?

Changing log level to debug for `com.vaadin.cdi.CdiInstantiator` logger in your application server should give some info.

Once the bean can be resolved, as pointed out in an answer, you have to use `@PonstConstruct` instead of constructor.

**Comment by madduci** [comment]
I don't have a `bean.xml` because Thorntail by default looks for all the available ones. 
There isn't any further extension for  `thorntail.elytron.wui.MainView`, it should be the main entrypoint for Vaadin

**Comment by kumm** [comment]
I'm afraid your application is not a bean archive, so your classes are not discovered by CDI.
As a quick try create an empty `beans.xml` in `WEB-INF`.
Please refer to https://docs.jboss.org/cdi/learn/userguide/CDI-user-guide.html#packaging-and-deployment

**Comment by kumm** [comment]
Checked Thorntail. The vaadin 10 example with CDI addon works after a beans.xml is added.
See https://github.com/kumm/thorntail-examples/commit/00fd4a4b6d4f610a16f22d14e04805ac12f69f31

**Comment by madduci** [comment]
I confirmed that adding the following bean.xml, it worked.
Excuse me for the issue

`<beans xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns="http://xmlns.jcp.org/xml/ns/javaee"
       xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee
       http://xmlns.jcp.org/xml/ns/javaee/beans_2_0.xsd" bean-discovery-mode="all">
</beans>`
