### ISSUE TITLE
Abstract views annotated view Route are published

### ISSUE THREAD

**Issue by mstahv** [vaadin/cdi#279]
If one annotates an abstract view with Route annotation, it gets published (but navigating there naturally fails). Also, implementations of such classes are not published, like with Spring and plain servlet deployment. 

Tested with 12.0.6, with following classes:

```
@Route
public abstract class AbstractView extends VerticalLayout {
    
}

public class SomeView extends AbstractView {

    public SomeView() {
        add(new Paragraph("Some"));
    }

}
```

**Comment by kumm** [comment]
It seems to me it depends on application server whether descendant routes without `@Route` are discovered or not, even with plain servlet deployment. I found it is discovered on Jetty 9. But not on TomEE 7, or Wildfly 11, because `RouteRegistryInitializer.onStartup` does not get non annotated descendant classes. 
Is it possible you tried different deployments on different servers?

With CDI route targets are instantiated by bean type.
In the given example CDI will instantiate `SomeView` for the bean type `AbstractView`, if there are not any other descendants. If you have `class OtherView extends AbstractView` too, then CDI can't instantiate a bean for the bean type `AbstractView`, because it is ambiguous. In this case instantiation will fall back to default vaadin instantiation which will fail with an abstract class.
You can customize bean types for a bean with `@Typed` annotation.

**Comment by mstahv** [comment]
Might be that there is something application server specific too. I think I used the basic starters (or technically viritin Maven archetypes, which are based on those) -> jetty in plain servlet, tomcat in spring boot and wildfly in cdi.

The tomcat/spring-boot mechanism would feel most natural for me.

**Comment by kumm** [comment]
Currently I see 2 ways of route discovery ( 2+1 in fact ):
1) spring boot
Spring addon scans the classes for routes. It honours the inheritance of `@Route` annotation, and skips abstract classes. It is in `com.vaadin.flow.spring.VaadinServletContextInitializer.RouteServletContextListener#contextInitialized`
This way descendants are registered, abstract are not. We agree it makes sense.

2) vaadin servlet deployment ( regardless of CDI addon ) 
It relies on `javax.servlet.ServletContainerInitializer` machinery. Route classes provided by the application server to `RouteRegistryInitializer.onStartup` are registered. The abstract class with `@Route` is provided, but it seems to be application server specific whether descendant classes without explicit `@Route` are provided or not. Jetty provides, some others not. 
This way the route for the abstract class is registered, and vaadin tries to instantiate it if you navigate there.
This behaviour can be changed in flow.

**Comment by pleku** [comment]
I'm not entirely sure if this is still an issue to CDI since it was fixed for Spring Boot apps, but as there has not been any interaction on this issue, it doesn't seem like a priority to be fixed.

The users also should not be adding `@Route` to abstract classes other than by accident, so I'm going to close this issue instead of keeping it hanging for now.
