### ISSUE TITLE
UIScoped RouterLayout has issue on re-entering

### ISSUE THREAD

**Issue by roeltje25** [vaadin/cdi#324]
Hi,

I have a Routerlayout which is @UIScoped and it contains a @RouteScoped component with the RouterLayout as its parent layout via @Route annotation. In this nested component I trigger a navigation to another route which does not contain this parent layout. Afterwards I click the back button in the browser and the child component is added to the RouterLayout for a second time. 

When inspeciting calls to showRouterLayout and removeRouterLayout. I see that the @UIScoped routerlayout is removed per removeRouterLayout and then the new compoennt is added with showRouterLayout. which is ok. Then I click back and I see the new component gets removed, and the old @Uiscoped layout is added back (remember that the nested child was never removed) then the system adds a new copy of the @Routescoped child which results in double element in the page.

I hope this makes sense, please let me know if more information is required.
Roel

**Comment by roeltje25** [comment]
So please find attached the minimal example of the issue. you should be able to run it using mvn tomee:run
The issue talked about here is demonstrated by clicking on the text of oneview and then clicking on anotherview, and repeat this a few times. You will see oneview text gets repeated. Which should not happen if I understand the javadoc of RouterLayout showRouterLayoutContent correctly.

Additional issue is that the root page (connected to OneView via RouterAlias("")) does not seem to generate the required ParentLayout at all (which I would expect it to). Just found this out while testing the minimal example.
[parentlayout-issue-demo.zip](https://github.com/vaadin/cdi/files/4456421/parentlayout-issue-demo.zip)

**Comment by roeltje25** [comment]
Additionally, although I have this in a CDI project. I think this may not be a CDI issue, but an issue in the method com.vaadin.flow.component.internal.UIInternals.showRouteTarget (line 652 in UIInternals.java).  when you switch from a @route component ONE with parentlayout A nested withing parentlayout B to @route component TWO directly with parentlayout B. and then you go back, this code tries to remove @Route component ONE from parentlayout B, while it should actually remove parentlayout A frorm parentlayout B. At least, this is my hunch after a quick investigation.

**Comment by roeltje25** [comment]
*bump*

**Comment by roeltje25** [comment]
still *bump*

**Comment by denis-anisimov** [comment]
First of all:
in the example `@RouteScoped` annotation is used without any `RouteScopeOwner`  annotation which makes  `@RouteScoped`  no-op .
So I indeed doubt that this issue is a CDI issue.

On the other hand I couldn't reproduce the scenario from here: https://github.com/vaadin/cdi/issues/324#issuecomment-611534376.

Returning back to the view without interim parent layout doesn't call `removeRouterLayoutContent`  at all.
I will try to see what's going on without CDI.

**Comment by denis-anisimov** [comment]
I cannot reproduce the issue without CDI.

**Comment by denis-anisimov** [comment]
I cannot use the attached project to reproduce the issue: `mvn tomee:run` starts the server but there is no any deployed applicaiton.

**Comment by denis-anisimov** [comment]
The attached minimal example contains a lot of irrelevant things for this ticket:
- pom contains dependencies to Git which are extra for the ticket.
- Java files have templates which are extra for the ticket.

Finally after cleaning up dramatically the project I was able to run it via 
`mvn package tomee:run`.

Spent several hours on reproducing.

**Comment by roeltje25** [comment]
For me the issue does show when running this example with mvn package tomee:run strange it didn't work for you (I am running on windows btw).

I used a reduced example with CDI as I did not know what caused the problem

**Comment by denis-anisimov** [comment]
One of the reasons why it doesn't work is :
>to run it using mvn tomee:run

As I said: `mvn tomee:run` doesn't deploy the app.

`mvn package tomee:run` does what it should.

**Comment by denis-anisimov** [comment]
OK, now I understand the problem.

It's a consequence of  incorrect scopes usage.

Here is what happens:
- `SubLayout` instance is UI scoped and it's preserved after the first navigation AS IS (so One component is not removed from it as well).
- `OneView` has `@RouteScoped`  scope which (as I mentioned above) is always no-op without  `RouteScopeOwner`. Without `RouteScopeOwner`  explicitly specified the owner is the current parent which is `SubLayout`  instance but since this instance is not in the route anymore (after the first navigation) then the instance is not preserved anyhow. So it's recreated on "back".
- As a result  the `SubLayout` instance is reused on "back" and it contains "OneView" from the first try. Since "OneView" is not preserved the other instance is created and added to the `SubLayout` .
As a result : there are two  "OneView" instance.

This doesn't happen if "OneView" instance uses the correct scope.
The correct scope could be:
- `@UIScoped`  (same as `SubLayout` ).
-  `@RouteScoped` but with the qualifier `@RouteScopeOwner(MainLayout.class)` : `MainLayout`  instance is preserved in the route chain after navigation which means that the route scoped instance with this owner will be reused.

So this is an application mistake because of bad scope usages.

**Comment by roeltje25** [comment]
Dear Denis,

I would reopen this issue, but I do not have permission it seems.

I thank you for your thorough analysis of the problem. I have been thinking about it a lot yesterday and my conclusion is that it is a bit to early to judge that this is an application mistake. Let me elaborate. Vaadin CDI provides several scopes which govern the lifecycle of components. It is perfectly possible that I would like to have a component with a route that I want to be RouteScoped, for example, because I want it to reinitialize completely when hitting the route, or because it is memory intensive and should not be kept during the UI lifecycle, etc. It is also not farfetched that I would like to have a parentlayout which should be UIScoped as it bears context that should be kept. For example imagine a set of complex overview pages which can be controlled by a common topbar. The SubLayout may be that topbar which could keep the state for each child Route and the children could then be RouteScoped memory intensive pages.

It would be intuitive to be simply be able to use @UIScoped and @RouteScoped in this situation. I disagree that @RouteScopeOwner should be used, as the child components should indeed not be retained when navigating away and by default @RouteScopeOwner is set to the component itself (resulting in @RouteScoped not being a no-op btw, especially when bean-discovery=ANNOTATED).

Long story short, in case of Vaadin CDI it would be more sensible if when the old router content is decoupled from its RouterLayout that one should check if this content itself is also a RouterLayout. In that case it would make sense to continue decoupling child router content components from the nested RouterLayouts and so on. This would make that RouteScoped and UIScoped annotations would work more intuitively (I am insisting on this being more intuitive).

I have currently (after reading your analysis) a patch that would make this work, which I am attaching. I would be very grateful if this suggestion may be considered and do not hesitate to ask more deeply if things are not clear.

with kind regards,

Roel

[proposed-extension-to-UIInternals-for-issue-324.patch.txt](https://github.com/vaadin/cdi/files/4756691/proposed-extension-to-UIInternals-for-issue-324.patch.txt)

**Comment by denis-anisimov** [comment]
You may create another ticket.
I'm not convinced that there is a bug.
The `RouteScoped` scope works exactly as it's designed.
And its design is described in my comment.

It's totally OK that you disagree with its design.
The `RouteScoped` is not intuitively clear and requires accompanied `RouteScopeOwner` (if it's not specified then its the parent layout is used by default and this is no-op).
That's the reason why this scope has not been added to Spring add-on: it wasn't clear how exactly it should behave and how to design it properly.

So you may create a different ticket which will be an enhancement and propose a way how it should work and add a patch.

**Comment by roeltje25** [comment]
Hi Denis,

Thanks for your quick reply. The RouteScoped annotation clearly states in its documentation that:
"Omitting the RouteScopeOwner annotation means owner is the bean itself." Which I would expect to work as such. The owner is the bean itself as such it should be out of scope after navigating away. About Spring I do not know much, but in CDI when using bean-discovery=ANNOTATED, a component should be annotated with a bean defining annotation, such as @RouteScoped. Ommitting that annotation would break things. This makes it not a no-op.

@RouteScoped as such defines a bean to be a CDI bean AND should have that bean be the RouteScopeOwner as per the documentation. This would imply that it gets out of scope when navigating to another route. For a developer which uses the framework as a black box (as they normally should) it would therefore be intuitively wrong, and unexpected - as per the documentation - that on navigating back a component would still be attached. I still insist on this being a bug. If not at least there is a problem with the documentation for @RouteScoped.

I am looking forward to your thoughts on this. Am I missing some other part of the documentation?

with kind regards,

Roel

**Comment by denis-anisimov** [comment]
>bean itself

yeah, may be , I don't remember already. But that's definitely no-op.
The bean itself is definitely not in the routing scope after removing so I don't even understand 
how you may expect it working anyhow.
>The owner is the bean itself as such it should be out of scope after navigating away. 

Yes, it's out of the scope.
The same happens when you don't use `@RouteScoped` at all (why `@RouteScoped` if mentioned then at all here if it's behavior in this case is exactly the same as without it?).
That's the reason. It should be in the scope. There is a check in the chain which prevents adding the same instance in the routing chain.
If the bean is not preserved then the new instance is created and the check (with already existing component) fail : the child component exists in the `SubLayout` , no-one removed it.

The problem is not in the `OneView` instance , the problem is in `SubLayout`: it's preserved as is with all its children.

So you have to use the same scope for the bean in the `SubLayout`  as `SubLayout` has otherwise the new instance will be created and will be added again: that's what happens.

Please reread the explanation : https://github.com/vaadin/cdi/issues/324#issuecomment-640521300

As said: this is not a bug. The explanation how it's designed is provided.
If you think `@RouteScoped` should work the other way (or router layout because of scopes) then please create another ticket.
