### ISSUE TITLE
Spike: review feedback for RouteScope

### ISSUE THREAD

**Issue by pleku** [vaadin/cdi#365]
Check and test the following issues:
- https://github.com/vaadin/cdi/issues/343
- https://github.com/vaadin/cdi/issues/345

This is to understand if we need to change how it works or add new features to support more use cases

**Comment by mshabarov** [comment]
These two issues have been tested based on CDI skeleton starter for platform `20.0.0.alpha8`.
Appropriate comments were given in the comment to these issues.
In short:
- #343 is not an issue at all, additional clarification requested from author.
- #345 qualified as a bug. Should be fixed on flow side (in order to avoid similar issues in Spring add-on), or documented how to use scopes properly.
