### ISSUE TITLE
Constructor Injection only works with CDI Beans

### ISSUE THREAD

**Issue by Flize** [vaadin/cdi#391]
According to the documenation at https://vaadin.com/docs/latest/integrations/cdi/instantiated-beans
> If the type is not found as a CDI bean – for example, because it is ambiguous or does not have a no-arguments public constructor – instantiation falls back to the default Vaadin behavior, and the component is instantiated as a plain-old Java object (POJO). Dependency injection is performed after instantiation, and injects still work, but other CDI features do not. The reason for this is that the instantiated component is not a contextual instance.

Actually, if the type is not found as a CDI bean
- a no-args or var-args constructor is required, see [ReflectTools.createInstance(Class)](https://github.com/vaadin/flow/blob/master/flow-server/src/main/java/com/vaadin/flow/internal/ReflectTools.java#L480)
- only field injection is performed, see [AbstractCdiInstantiator.getOrCreate(Class)](https://github.com/vaadin/cdi/blob/master/vaadin-cdi/src/main/java/com/vaadin/cdi/AbstractCdiInstantiator.java#L67)

Consequently

- constructor injection only works with CDI beans
- the flow-cdi-tutorial and the examples on https://vaadin.com/docs/latest/integrations/cdi/contexts only work with [bean-discovery-mode="all"](https://github.com/vaadin/flow-cdi-tutorial/blob/master/src/main/webapp/WEB-INF/beans.xml) because they use constructor injection

Please update the documentation or treat it as a bug.

**Comment by Legioth** [comment]
The quoted documentation says "Dependency injection is performed after instantiation", which implies that calling the constructor (i.e. instantiation) happens without support for injection. It could still be good to tweak the documentation to explicitly mention constructor injection since that's the terminology that a CDI user would be more familiar with.

**Comment by Legioth** [comment]
Document update in https://github.com/vaadin/docs/pull/1607

**Comment by roeltje25** [comment]
<blockquote>
the flow-cdi-tutorial and the examples on https://vaadin.com/docs/latest/integrations/cdi/contexts only work with [bean-discovery-mode="all"](https://github.com/vaadin/flow-cdi-tutorial/blob/master/src/main/webapp/WEB-INF/beans.xml) because they use constructor injection
</blockquote>
Actually, I have already reported a bug earlier about bean-discovery-mode="annotated" not working. This is because of a bug in the scope annotations @RouteScoped and @UIScoped. They should contain the meta-annotation @Stereotype as mentioned in the CDI spec here: https://docs.jboss.org/cdi/spec/1.2/cdi-spec.html#bean_defining_annotations

refer to the issue I reported here: https://github.com/vaadin/cdi/issues/303
I am still a bit sad that bug has not been fixed yet, while it is so 1) obvious, and 2) easy

**Comment by TatuLund** [comment]
I made a custom build of the Vaadin's CDI integration where these scopes are annotated with `@Stereotype`. In my case I still need bean-discovery-mode="all" in order to constructor injection to work. So based on my experiments it is not enough.

**Comment by TatuLund** [comment]
Nevertheless I opended a draft PR with the changes I made so that you can comment what I have missing. What I see in my testing however is that there seems not to be detrimental effect due this. https://github.com/vaadin/cdi/pull/392

**Comment by TatuLund** [comment]
Actually I did get my test app work, but it seems that with `@Stereotype` and bean-discovery-mode="annotated" you still need to have Routes annotated with `@RouteScope`and `@RouteScopeOwner`.

**Comment by roeltje25** [comment]
For me constructor injection works fine when using  bean-discovery-mode="annotated" When adding @Stereotype to the @RouteScoped Annotation. I do indeed need a @RouteScoped or @UISCoped annotation on the routes. This is logical as @Route is not a bean defining annotation. 

I can imagine making @Route a bean defining annotation may be more involved and may break some things in other places, or force dependencies on Jakarta that you may not want.

For using CDI therefore, I would update the documentation that Routes should always be annotated with @RouteScoped or @UISCoped in case one uses CDI with bean-discovery-mode="annotated".

**Comment by TatuLund** [comment]
> For using CDI therefore, I would update the documentation that Routes should always be annotated with @RouteScoped or @UISCoped in case one uses CDI with bean-discovery-mode="annotated".

Yes, if we accept the PR I made, this clarification is necessary. That was the point of my earlier comment.

**Comment by TatuLund** [comment]
> I can imagine making `@route` a bean defining annotation may be more involved and may break some things in other places, or force dependencies on Jakarta that you may not want.

That would require most likely require extending Router to support the new replacement annotation. That will require more study. It is probably doable.
